[package]
name = "rust_quick_guide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.5"
futures = "0.3.30"
rand = "0.8.5"
tokio = { version ="1.35.1", features = ["full"] }
